<?php

namespace App\Http\Controllers\Api\OAuth;

/**
 * @OA\Schema(
 *     schema="IssueTokenRequest",
 *     oneOf={
 *         @OA\Schema(
 *             @OA\Property(
 *                 property="grant_type",
 *                 type="string",
 *                 example="password",
 *             ),
 *             @OA\Property(
 *                 property="client_id",
 *                 type="string",
 *                 example="1",
 *             ),
 *             @OA\Property(
 *                 property="client_secret",
 *                 type="string",
 *                 example="qqMLRiwnswM68feyiehAVwBbg6yqAfNYEdDE9fnl",
 *             ),
 *             @OA\Property(
 *                 property="username",
 *                 type="string",
 *                 example="me@example.com"
 *             ),
 *             @OA\Property(
 *                 property="password",
 *                 type="string",
 *                 example="password",
 *             ),
 *             @OA\Property(
 *                 property="scope",
 *                 type="string",
 *                 example="",
 *             ),
 *         ),
 *         @OA\Schema(
 *             @OA\Property(
 *                 property="grant_type",
 *                 type="string",
 *                 example="social",
 *             ),
 *             @OA\Property(
 *                 property="client_id",
 *                 type="string",
 *                 example="1",
 *             ),
 *             @OA\Property(
 *                 property="client_secret",
 *                 type="string",
 *                 example="qqMLRiwnswM68feyiehAVwBbg6yqAfNYEdDE9fnl",
 *             ),
 *             @OA\Property(
 *                 property="network",
 *                 type="string",
 *                 enum={"facebook"},
 *                 example="facebook"
 *             ),
 *             @OA\Property(
 *                 property="access_token",
 *                 type="string",
 *                 example="",
 *             ),
 *             @OA\Property(
 *                 property="scope",
 *                 type="string",
 *                 example="",
 *             ),
 *         ),
 *     },
 * )
 *
 * @OA\Schema(
 *     schema="IssueTokenResponse",
 *     type="object",
 *     @OA\Property(
 *         property="token_type",
 *         type="string",
 *         example="Bearer",
 *     ),
 *     @OA\Property(
 *         property="expires_in",
 *         type="integer",
 *         example="31536000",
 *     ),
 *     @OA\Property(
 *         property="access_token",
 *         type="string",
 *     ),
 *     @OA\Property(
 *         property="refresh_token",
 *         type="string",
 *     ),
 * )
 *
 * @OA\Post(
 *     path="/oauth/token",
 *     operationId="auth.oauth.token",
 *     tags={"Auth"},
 *     @OA\RequestBody(
 *         required=true,
 *         @OA\MediaType(
 *             mediaType="application/json",
 *             @OA\Schema(ref="#/components/schemas/IssueTokenRequest")
 *         )
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="OK",
 *         @OA\JsonContent(ref="#/components/schemas/IssueTokenResponse")
 *     ),
 * )
 *
 */
